name: nutrition
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  image_picker: ^1.2.1
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2

  google_generative_ai: ^0.4.7
  firebase_auth: ^6.1.2
  uuid: ^4.5.2
  dotted_border: 2.1.0
  fl_chart: ^1.1.1
  permission_handler: ^11.0.1
  googleapis: ^11.4.0
  http: ^1.1.0
  js: ^0.6.6
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  mockito: ^5.5.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/data/nutrition.csv