// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQ76n5gPZgQRBH2oq4ojmbry-8__iuIA',
    appId: '1:1086613473742:web:7834e3199e2184f8fd039f',
    messagingSenderId: '1086613473742',
    projectId: 'nutritionanalyzer-6485e',
    authDomain: 'nutritionanalyzer-6485e.firebaseapp.com',
    storageBucket: 'nutritionanalyzer-6485e.firebasestorage.app',
    measurementId: 'G-KVPXPC3FB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwS2IswiYpPj2yVOliJjIu_fggacJQc6k',
    appId: '1:1086613473742:android:39ffc3d1623ab1e6fd039f',
    messagingSenderId: '1086613473742',
    projectId: 'nutritionanalyzer-6485e',
    storageBucket: 'nutritionanalyzer-6485e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zko1nTawu9RiVUJe7YD-UCK7fBUDawM',
    appId: '1:1086613473742:ios:42138b3cc52d57a1fd039f',
    messagingSenderId: '1086613473742',
    projectId: 'nutritionanalyzer-6485e',
    storageBucket: 'nutritionanalyzer-6485e.firebasestorage.app',
    iosBundleId: 'com.example.nutrition',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2zko1nTawu9RiVUJe7YD-UCK7fBUDawM',
    appId: '1:1086613473742:ios:42138b3cc52d57a1fd039f',
    messagingSenderId: '1086613473742',
    projectId: 'nutritionanalyzer-6485e',
    storageBucket: 'nutritionanalyzer-6485e.firebasestorage.app',
    iosBundleId: 'com.example.nutrition',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQ76n5gPZgQRBH2oq4ojmbry-8__iuIA',
    appId: '1:1086613473742:web:690cd2db0e94c7fafd039f',
    messagingSenderId: '1086613473742',
    projectId: 'nutritionanalyzer-6485e',
    authDomain: 'nutritionanalyzer-6485e.firebaseapp.com',
    storageBucket: 'nutritionanalyzer-6485e.firebasestorage.app',
    measurementId: 'G-P6ZL2E8SQ9',
  );
}
